version: '3.2'

services:
  application:
    image: maven:3.6.3-jdk-11-slim
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DB}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - MAVEN_OPTS=-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
    volumes:
      - ./:/root/service
      - ~/.m2:/root/.m2:cached
    working_dir: /root/service
    command: /bin/sh -c "ls -la && ./wait-for-it.sh db:3306 -s -t 90 -- mvn clean spring-boot:run"
    networks:
      - java-application

  db:
    image: mysql:latest
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: security
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - java-application

networks:
  java-application:
    driver: bridge